theme: hugo-book

disableKinds:
  - taxonomy
  - term
  - RSS
  - sitemap

buildFuture: true
mainContent: cpp
defaultContentLanguage: pl
defaultContentLanguageInSubdir: true
enableGitInfo: true

languages:
  pl:
    languageName: Polski (Informatyka)
    title: Programowanie 2
    weight: 1
    homeSection: cpp

params:
  BookTheme: "auto"
  BookSection: "*"

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      linkify: false
  highlight:
    noclasses: false

minify:
  minifyOutput: true
