baseURL: "http://cpp.mini.pw.edu.pl/"
title: "Programowanie 2 - Obiektowe"
theme: hugo-book

disableKinds:
  - taxonomy
  - term
  - RSS
  - sitemap

disablePathToLower: true
defaultContentLanguage: pl
#defaultContentLanguageInSubdir: true
enableGitInfo: true

languages:
  pl:
    languageName: Polski (Informatyka)
    title: Programowanie 2
    weight: 1

params:
  BookTheme: "auto"
  BookSection: "*"
  BookRepo: https://github.com/CPP-MINI/cpp-site
  BookEditPath: edit/master
  BookCommitPath: commit
  BookDateFormat: '2 January 2006'

menu:
  after:
    - name: "Github"
      url: https://github.com/CPP-MINI/cpp-site
      weight: 10

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      linkify: false
  highlight:
    noclasses: false

minify:
  minifyOutput: true
