theme: hugo-book

disableKinds:
  - taxonomy
  - term
  - RSS
  - sitemap

buildFuture: true
defaultContentLanguageInSubdir: true
enableGitInfo: true

languages:
  pl:
    languageName: Polski (Informatyka)
    title: Programowanie 2 - Obiektowe
    weight: 1

params:
  BookTheme: "auto"
  BookSection: "*"

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      linkify: false
  highlight:
    noclasses: false

minify:
  minifyOutput: true
