on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-hugo:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.140.2'
          extended: true

      - name: Build Hugo Site
        run: hugo

      - name: Build Completed
        run: echo "Hugo site built successfully!"
